### ISSUE TITLE
Nit: Remove duplicate settings in theme.json

### ISSUE THREAD

**Issue by carolinan** [yithemes/yith-wonder#14]
In theme.json, there are settings that are enabled by the `appearanceTools`, and enabled again further down in the file. This is unnecessary.

spacing: blockGap, margin, padding
border: color, radius, style, width

**Comment by carolinan** [comment]
Ah, also, the default value for Typography > DropCap is true, so this could also be removed.

**Comment by francgrasso** [comment]
This is what happens when you start testing settings and then forget to review what you leave in the theme.json file. Thanks Carolina!
