### ISSUE TITLE
Comments form: Submit button text color is the same as the background color

### ISSUE THREAD

**Issue by carolinan** [yithemes/yith-wonder#18]
When I activate the theme on WordPress 6.6, the button below the comments form has a text color that is the same as the button background color. I only tested the default legacy comments block. I did not convert it to the newest comments block.

<img width="1166" alt="Comments form submit button is not readable" src="https://github.com/user-attachments/assets/b0d924fc-ede9-4c6e-a824-5592affb8a95">

**Comment by francgrasso** [comment]
Hello there,
this will be fixed with https://github.com/yithemes/yith-wonder/commit/e135525b6feff2c910d437b59ad0fb97802c5a6c 
I'm working on the update of the theme now

**Comment by carolinan** [comment]
Thank you.

**Comment by francgrasso** [comment]
Solved in version 2.1.0 of the theme
